Copn.EndPoint/Models/CouponDto.cs
namespace Coupon.EndPoint.Models
{
    public class CouponDto
    {
        public int Id { get; set; }
        public string CouponCode { get; set; }
        public string DiscountAmount { get; set; }
        public string MinAmount { get; set; }
    }
}

Copn.EndPoint/Models/RequestDto.cs
using static Coupon.EndPoint.Utility.SD;

namespace Coupon.EndPoint.Models
{
    public class RequestDto
    {
        public ApiType ApiType { get; set; } = ApiType.GET;
        public string Url { get; set; }
        public object Data { get; set; }
        public string AccessToken { get; set; }
    }
}

Copn.EndPoint/Models/ResponseDto.cs
namespace Coupon.EndPoint.Models
{
    public class ResponseDto
    {
        public object? Result { get; set; }
        public bool IsSuccess { get; set; } = true;
        public string Message { get; set; } = "";
    }
}

Copn.EndPoint/Controllers/CouponController.cs
using Coupon.EndPoint.Models;
using Coupon.EndPoint.Services.Contracts;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Coupon.EndPoint.Controllers
{
    public class CouponController : Controller
    {
        private readonly ICouponService _couponService;

        public CouponController(ICouponService couponService)
        {
            _couponService = couponService;
        }
        public async Task<IActionResult> Index()
        {
            List<CouponDto> couponList = new();

            ResponseDto? response = await _couponService.GetAllCouponAsync();

            if (response != null && response.IsSuccess)
            {
                couponList = JsonConvert.DeserializeObject<List<CouponDto>>(Convert.ToString(response.Result));
            }
            else
            {
                TempData["error"] = response?.Message;
            }
            return View(couponList);
        }

        public async Task<IActionResult> CouponCreate()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CouponCreate(CouponDto? coupon)
        {
            if (ModelState.IsValid)
            {
                ResponseDto response = await _couponService.CreateCouponAsync(coupon);

                if (response != null && response.IsSuccess)
                {
                    return Redirect(nameof(Index));
                }
                else
                {
                    TempData["error"] = response?.Message;
                }
            }
            return View(coupon);
        }


        [HttpGet]
        public async Task<IActionResult> CouponDelete(int id)
        {
            ResponseDto? response = await _couponService.GetCouponByIdAsync(id);
            if (response != null && response.IsSuccess)
            {
                CouponDto? model = JsonConvert.DeserializeObject<CouponDto>(Convert.ToString(response.Result));
                return View(model);
            }
            else
            {
                TempData["error"] = response?.Message;
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> CouponDelete(CouponDto couponDto)
        {
            ResponseDto? response = await _couponService.DeleteCouponAsync(couponDto.Id);

            if (response != null && response.IsSuccess)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                TempData["error"] = response?.Message;
            }
            return View(couponDto);
        }
    }
}

Copn.EndPoint/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Coupon.EndPoint.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Copn.EndPoint/Views/Coupon/CouponCreate.cshtml
@model CouponDto

<form asp-controller="Coupon" asp-action="CouponCreate" method="post">
    <fieldset>
        <legend>Create Coupon</legend>
        <div class="form-group w-25">
            <label class="form-label mt-4" asp-for="CouponCode">Coupon Code</label>
            <input type="text" class="form-control" asp-for="CouponCode">
            <span class="text-danger" asp-validation-for="CouponCode"></span>
        </div>
        <div class="form-group  w-25">
            <label class="form-label mt-4" asp-for="DiscountAmount">Discount Amount</label>
            <input type="text" class="form-control" asp-for="DiscountAmount">
            <span class="text-danger" asp-validation-for="DiscountAmount"></span>
        </div>
        <div class="form-group  w-25">
            <label class="form-label mt-4" asp-for="MinAmount">Min Amount</label>
            <input type="text" class="form-control" asp-for="MinAmount">
            <span class="text-danger" asp-validation-for="MinAmount"></span>
        </div>

        <button type="submit" class="btn btn-dark mt-3">Submit</button>
        <a class="btn btn-light mt-3" asp-controller="Coupon" asp-action="Index">Back to list</a>
    </fieldset>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Copn.EndPoint/Views/Coupon/CouponDelete.cshtml
@model CouponDto

<form asp-action="CouponDelete" method="post">
    <input asp-for="Id" type="hidden"  />

        <legend>Delete Coupon</legend>
        <div class="form-group w-25">
            <label class="form-label mt-4" asp-for="CouponCode">Coupon Code</label>
            <input type="text" class="form-control" asp-for="CouponCode">
            <span class="text-danger" asp-validation-for="CouponCode"></span>
        </div>
        <div class="form-group  w-25">
            <label class="form-label mt-4" asp-for="DiscountAmount">Discount Amount</label>
            <input type="text" class="form-control" asp-for="DiscountAmount">
            <span class="text-danger" asp-validation-for="DiscountAmount"></span>
        </div>
        <div class="form-group  w-25">
            <label class="form-label mt-4" asp-for="MinAmount">Min Amount</label>
            <input type="text" class="form-control" asp-for="MinAmount">
            <span class="text-danger" asp-validation-for="MinAmount"></span>
        </div>

        <button type="submit" class="btn btn-dark mt-3">Delete</button>
        <a class="btn btn-light mt-3" asp-controller="Coupon" asp-action="Index">Back to list</a>
  
</form>

Copn.EndPoint/Views/Coupon/Index.cshtml
@model IEnumerable<CouponDto>


<a class="btn btn-dark mt-4" asp-controller="Coupon" asp-action="CouponCreate">Create New Coupon</a>
@if (Model.Any())
{
    <table class="table table-striped table-dark mt-3">

        <thead>
            <tr>

                <th scope="col">CouponCode</th>
                <th scope="col">DiscountAmount</th>
                <th scope="col">MinAmount</th>
                <th>Operations</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>

                    <td>@item.CouponCode</td>
                    <td>@item.DiscountAmount</td>
                    <td>@item.MinAmount$</td>
                    <td>
                        <a asp-action="CouponDelete" asp-route-id="@item.Id">
                            <i class="fa fa-duotone fa-trash mx-4 text-light icon-link-hover" style="font-size:30px"></i>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h1 class="text-danger align-content-center">No data was inserted!</h1>
}

Copn.EndPoint/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Copn.EndPoint/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Copn.EndPoint</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Coupon.EndPoint.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Coupon.EndPoint</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link active" href="#">Home
                                <span class="visually-hidden">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">About</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Content Management</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-controller="Coupon" asp-action="Index">Coupon</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <a class="dropdown-item" href="#">Something else here</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Separated link</a>
                            </div>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-sm-2" type="search" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            <partial name="_Notfications"/>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Copn.EndPoint - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Copn.EndPoint/Views/Shared/_Notfications.cshtml
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" ></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]')
    </script>
}
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["error"]')
    </script>

}